// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/IM-Lite/IM-Lite-Server/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/im/v1/conversation/list",
					Handler: GetConversationListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/im/v1/message/pull/batch",
					Handler: PullMessagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/im/v1/message/send",
					Handler: SendMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/im/v1/conversation/clear/unread",
					Handler: ClearUnreadCountHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/im/v1/conversation/clear/history",
					Handler: ClearHistoryHandler(serverCtx),
				},
			}...,
		),
	)
}
