// Code generated by goctl. DO NOT EDIT.
package types

type ReqGetConversationList struct {
}

type RespGetConversationList struct {
	Message []byte `json:"message"`
}

type ReqPullMessages struct {
	Message []byte `json:"message"`
}

type RespPullMessages struct {
	MessageLists []byte `json:"messages"`
}

type ReqSendMessage struct {
	Message []byte `json:"message"`
}

type RespSendMessage struct {
	FailedMsg string `json:"failedMsg"`
}

type ReqClearUnreadCount struct {
	ConvId string `json:"convId"`
}

type RespClearUnreadCount struct {
}

type ReqClearHistory struct {
	ConvId string `json:"convId"`
}

type RespClearHistory struct {
}
